# Generated by Django 5.0.6 on 2024-07-03 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('id_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.entity')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectAttributeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.attribute')),
                ('id_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.entity')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectFieldValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('id_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.entityfield')),
                ('id_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.object')),
            ],
        ),
    ]
